version: '2'

services:
  web:
    build: src/.
    ports:
      - "3000:3000"   #web service port
      - "5859:5859"   #debug port
    volumes:
      - ./:/queuebull
    networks:
        - queue-network
    working_dir: /queuebull
    command: sh -c "npm install && cd src && dotenv -e .env.production npx prisma migrate dev && npm run dev"
    depends_on:
      - db
      - redis
    container_name: web
    
  db:
    build: database/.
    ports:
      - "5432:5432"
    networks:
        - queue-network
    container_name: database

  redis:
    build: redis/.
    # command: redis-server
    ports:
      - "6379:6379"
    networks:
      - queue-network
    container_name: redis

networks:
  queue-network:
    driver: bridge